# Generated by Django 2.0.13 on 2019-04-29 21:18

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('climatecontroller', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CarbonDioxideController',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('controller_ip', models.GenericIPAddressField()),
                ('controller_gpio', models.PositiveSmallIntegerField()),
                ('control_mode', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='HumidityController',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('controller_ip', models.GenericIPAddressField()),
                ('controller_gpio', models.PositiveSmallIntegerField()),
                ('preffered_value', models.FloatField(default=30.0, validators=[django.core.validators.MinValueValidator(30.0), django.core.validators.MaxValueValidator(60.0)])),
                ('control_mode', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='TemperatureController',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('controller_ip', models.GenericIPAddressField()),
                ('controller_gpio', models.PositiveSmallIntegerField()),
                ('preffered_value', models.FloatField(default=22.0, validators=[django.core.validators.MinValueValidator(16.0), django.core.validators.MaxValueValidator(30.0)])),
                ('control_mode', models.BooleanField(default=True)),
            ],
        ),
        migrations.DeleteModel(
            name='CarbonDioxideSensor',
        ),
        migrations.DeleteModel(
            name='HumiditySensor',
        ),
        migrations.DeleteModel(
            name='TemperatureSensor',
        ),
    ]
