# Generated by Django 2.0.13 on 2019-05-09 18:37

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('climatecontroller', '0002_auto_20190430_0018'),
    ]

    operations = [
        migrations.AddField(
            model_name='carbondioxidecontroller',
            name='max_value',
            field=models.FloatField(default=10000.0, validators=[django.core.validators.MinValueValidator(2000.0), django.core.validators.MaxValueValidator(10000.0)]),
        ),
        migrations.AddField(
            model_name='carbondioxidecontroller',
            name='min_value',
            field=models.FloatField(default=2000.0, validators=[django.core.validators.MinValueValidator(2000.0), django.core.validators.MaxValueValidator(10000.0)]),
        ),
        migrations.AddField(
            model_name='humiditycontroller',
            name='delta',
            field=models.FloatField(default=1.0, validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(5.0)]),
        ),
        migrations.AddField(
            model_name='temperaturecontroller',
            name='delta',
            field=models.FloatField(default=1.0, validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(5.0)]),
        ),
    ]
